name: celeb-matcher

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8003:80
    depends_on:
      - backend
      - frontend
  frontend:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/:/home/node/app
    expose:
      - "3000"
    ports:
      - "8001:3000"
    command: "npm start"
  backend:
    image: celeb-matcher/backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8002:3001"
    command: "python src/server.py"